### PR TITLE
Use 2.x version of coffee-react

### PR DESCRIPTION
**Pull request by ropez**
The commit is made by @emmenko
Can you please update the npm package, as the current version is incompatible with the current version of react?

### CODE REVIEW

**Comment by mtscout6** [comment]
Is there a reason you are changing the url of the repo, and homepage?

**Comment by emmenko** [comment]
@mtscout6 I changed it because it was a fork and didn't consider making a PR. I can adjust it for the PR though...

**Comment by emmenko** [comment]
PR here https://github.com/mtscout6/mimosa-cjsx/pull/2

**Comment by mtscout6** [comment]
Closing in favor of #2

**Pull request closed without merging**
