### PR TITLE
Use 2.x version of coffee-react

### PR DESCRIPTION
**Pull request by emmenko**

### CODE REVIEW

**Comment by mtscout6** [comment]
Can you squash those?

**Comment by ropez** [comment]
@mtscout6 if you're onboard with the general idea of updating to be compatible with the current React, I suggest you just change the version yourself. I could of course do a PR, but I assume you need to change the version number of this package as well, and you should be in charge of that.

**Comment by mtscout6** [comment]
I'm thinking it would actually be best to move this to being a peer dependency and opening the restriction to anything greater than 2.0. This way you can control the version of coffee-react that you want yourself and as long as the public api of coffee-react doesn't change then it will work. The api hasn't changed in nearly a year or more, and is unlikely to change since the api we care about is small in scope. What are your thoughts about this?

**Comment by emmenko** [comment]
@mtscout6 good idea!! :+1:

**Comment by mtscout6** [comment]
closing in favor of #3

**Pull request closed without merging**
